### ISSUE TITLE
Web 端基于机器学习实现防档（不挡脸）弹幕 | 风痕的博客

### ISSUE THREAD

**Issue by hughfenghen** [hughfenghen/hughfenghen.github.io#101]
https://hughfenghen.github.io/fe/body-mask-danmaku/ 

 ...

**Comment by xuchao996** [comment]
大佬你好，请问下”此时，CPU 占用 5% 左右“ 这句话下面那张图是什么工具生成的？

**Comment by hughfenghen** [comment]
> @xuchao996
> 大佬你好，请问下”此时，CPU 占用 5% 左右“ 这句话下面那张图是什么工具生成的？

Kap 录屏 chrome devtools 性能监控界面，导出 gif
