### ISSUE TITLE
JS 正则表达式基础 | 风痕的博客

### ISSUE THREAD

**Issue by hughfenghen** [hughfenghen/hughfenghen.github.io#116]
https://hughfenghen.github.io/fe-basic-course/js-regex-basic/ 

 ...

**Comment by hughfenghen** [comment]
1

**Comment by eric755** [comment]
\s示例有误
应该是：/\s/.test(' ')

**Comment by hughfenghen** [comment]
> @eric755
> \s示例有误
> 应该是：/\s/.test(' ')

thx，已更正
