### ISSUE TITLE
网站怎么换风格了，我感觉没以前鲜明

### ISSUE THREAD

**Issue by ihsz-OldFriend** [hughfenghen/hughfenghen.github.io#167]
https://hughfenghen.github.io/

**Comment by hughfenghen** [comment]
@ihsz-OldFriend 昨天刚换的
之前是文档风格，实际内容是博客站点  ：）

风挡风格缺点：
1. 没有博客基本 tag 功能，标准化的日期 等
2. 是按目录管理内容的，内容多了之后不好管理，有些时候很难给文章分目录
3. 文章切换目录后URL会变化，对搜索引擎、外链不友好

犹豫（拖延）了很久，还是决定改了
