### ISSUE TITLE
增加RSS订阅

### ISSUE THREAD

**Issue by laddwong** [hughfenghen/hughfenghen.github.io#172]
感谢你分享的技术和文章，给我的工作提供了巨大的帮助。希望可以增加RSS订阅，以及时获取你的更新。再次感谢

**Comment by hughfenghen** [comment]
好的，我过几天加上

**Comment by hughfenghen** [comment]
@laddwong  加上了
https://hughfenghen.github.io/rss.xml

**Comment by laddwong** [comment]
已订阅，感谢。
