### ISSUE TITLE
[Issue]: #header 的 100vw 会导致出现横向滚动条

### ISSUE THREAD

**Issue by bifan** [hughfenghen/hughfenghen.github.io#200]
如果元素设置了 `width:100vw`，那么宽度将是 `「100%」+「垂直滚动条宽度」`。导致出现横向滚动条

## 100vw

![CleanShot 2024-04-03 at 15 06 18@2x](https://github.com/hughfenghen/hughfenghen.github.io/assets/2929293/aa2fe324-8cc2-4f5c-8f82-970ce75fe6fb)

## ~~100vw~~

![CleanShot 2024-04-03 at 15 10 10@2x](https://github.com/hughfenghen/hughfenghen.github.io/assets/2929293/116d2678-39ac-40b4-ae6e-0e73bf2b38d6)

**Comment by hughfenghen** [comment]
6，我博客的 Bug 都要提
我抽空改一下
