### ISSUE TITLE
hey  请问这个 bug 是什么时候发现的啊 ? 

### ISSUE THREAD

**Issue by cleverboy32** [hughfenghen/hughfenghen.github.io#62]
![image](https://user-images.githubusercontent.com/17595456/103643780-32236f00-4f90-11eb-9339-36f2f09dee31.png)

safari10 这样是针对 uglifyjs-webpack-plugin 2.2.0 生效吗？
希望看到能回复一下，在线修 bug @hughfenghen

**Comment by hughfenghen** [comment]
https://github.com/webpack-contrib/uglifyjs-webpack-plugin
你可以去这里找详细的支持版本
